/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_65dd53a20504ba69___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___js_sys_7fef9d8b37236acf___Array__web_sys_958e3501fe61ea89___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___sys__JsNullable_wgpu_997d1835e6e97232___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_f0fd674eaa06beef___result__Result_____wasm_bindgen_65dd53a20504ba69___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___sys__JsNullable_wgpu_997d1835e6e97232___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_f0fd674eaa06beef___result__Result_____wasm_bindgen_65dd53a20504ba69___JsError___true__11: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___sys__JsNullable_wgpu_997d1835e6e97232___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_f0fd674eaa06beef___result__Result_____wasm_bindgen_65dd53a20504ba69___JsError___true__12: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___js_sys_7fef9d8b37236acf___Function_fn_wasm_bindgen_65dd53a20504ba69___JsValue_____wasm_bindgen_65dd53a20504ba69___sys__Undefined___js_sys_7fef9d8b37236acf___Function_fn_wasm_bindgen_65dd53a20504ba69___JsValue_____wasm_bindgen_65dd53a20504ba69___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__3: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke___wasm_bindgen_65dd53a20504ba69___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const wasm_bindgen_65dd53a20504ba69___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
